const experience = [
  {
    role: "Sr. UX Engineer",
    company: "Workday",
    location: "Seattle, WA",
    period: "Oct 2022 - Present",
    link: "https://www.workday.com/",
    achievements: [
      "Architected and launched the Workday Marketplace using React and Node.js, expanding access for 500+ enterprise clients.",
      "Built the project from 0 to 1, partnered across time zones, and helped interview and hire contractors to support launch delivery.",
      "Led UI architecture and scalable front-end systems, with Docker-based development flows and Jenkins-driven CI/CD.",
      "Revamped key portions of the Workday website to improve user experience, performance, and design execution with Figma.",
      "Improved developer experience by modernizing the build pipeline, upgrading tooling, and standardizing Husky, ESLint, and Prettier.",
    ],
    stack: [
      "App Direct",
      "React",
      "TypeScript",
      "JavaScript",
      "HTML",
      "CSS",
      "Sass",
      "Node.js",
    ],
  },
  {
    role: "Sr. Software Engineer",
    company: "Willow",
    location: "Seattle, WA",
    period: "Mar 2021 - Oct 2022",
    achievements: [
      "Built web applications for smart buildings, smart poles, and smart rail initiatives.",
      "Used Tailwind CSS and Styled Components with Twin Macro to deliver flexible UI systems.",
    ],
    stack: [
      "React",
      "JavaScript",
      "HTML",
      "CSS",
      "Sass",
      "Node.js",
      "ES6",
      "Figma",
      "Twin Macro",
    ],
  },
  {
    role: "Sr. Software Engineer (Front End)",
    company: "Microsoft",
    location: "Redmond, WA",
    period: "Oct 2019 - Mar 2021",
    achievements: [
      "Developed front-end features in Angular for Microsoft Azure Portal and Studio.",
      "Used PrimeNG to accelerate UI delivery and maintained a large, evolving production codebase.",
      "Built internal monitoring experiences for data engineers running Spark and SQL jobs.",
    ],
    stack: [
      "Angular",
      "JavaScript",
      "TypeScript",
      "HTML",
      "CSS",
      "Sass",
      "Node.js",
    ],
  },
  {
    role: "Software Engineer II (Frontend)",
    company: "T-Mobile",
    location: "Bothell, WA",
    period: "Apr 2018 - Oct 2019",
    achievements: [
      "Built Angular and TypeScript applications supporting T-Mobile call center workflows.",
      "Focused on dynamic UI behavior and front-end application reliability.",
    ],
    stack: [
      "Angular",
      "JavaScript",
      "TypeScript",
      "HTML",
      "CSS",
      "Sass",
      "Node.js",
    ],
  },
  {
    role: "Front End Developer",
    company: "Mapal",
    location: "Germany",
    period: "Oct 2017 - Apr 2018",
    achievements: [
      "Migrated an application from Angular 1.5 to Angular 5 using ngUpgrade.",
      "Helped modernize the codebase while preserving delivery momentum.",
    ],
    stack: [
      "Angular 5",
      "JavaScript",
      "HTML",
      "CSS",
      "Sass",
      "Node.js",
      "ngUpgrade",
    ],
  },
  {
    role: "Senior Developer (Frontend)",
    company: "AT&T",
    location: "Seattle, WA",
    period: "Apr 2016 - Sep 2017",
    achievements: [
      "Owned a primary component of the AT&T website experience.",
      "Delivered pixel-precise UI implementation based on business and design guidance.",
    ],
    stack: ["AngularJS", "JavaScript", "HTML", "CSS", "Sass", "Node.js"],
  },
];

export default experience;
